/*
 This should contain all ability information
 */

var Abilities = [
	// Ability list here in json format
	{
		"item_id": 2500,
		"required_type": "melee",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.8,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2501,
		"required_type": "melee",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.3,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.7,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2502,
		"required_type": "melee",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.1,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.6,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2503,
		"required_type": "bladed",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.9,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2504,
		"required_type": "bladed",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.3,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.8,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2505,
		"required_type": "melee",
		"aoe_size": 180,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 1,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.7,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2506,
		"required_type": "melee",
		"aoe_size": 180,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 1,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.9,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2507,
		"required_type": "pierce",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.9,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2508,
		"required_type": "blunt",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.3,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 0,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.9,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	},
	{
		"item_id": 2509,
		"required_type": "bladed",
		"aoe_size": 90,
		"range": 5,
		"cool_down": 2,
		"cast_time": 0.6,
		"type": "offensive",
		"duration": 0,
		"projectiles": 0,
		"piercing": 1,
		"projectile_speed": 0,
		"range_damage_modifier": 1,
		"damage_modifier": 0.8,
		"damage": 0,
		"armor": 0,
		"move_distance": 0,
		"ignore_armor": 0,
		"multiple_attacks": 0,
		"bleed_damage": 0,
		"stun": 0,
		"range_modifier": 0
	}
];

module.exports = Abilities;
