/*
  This should contain all item information
*/

var Items = [
	{
		"item_id": 1000,
		"name": "Healing Herb I",
		"purpose": "H_Heal",
		"buy_price": 10,
		"sell_price": 5,
		"required_level": 1,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 10
	},
	{
		"item_id": 1001,
		"name": "Status Herb I",
		"purpose": 0,
		"buy_price": 10,
		"sell_price": 5,
		"required_level": 1,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 0
	},
	{
		"item_id": 1002,
		"name": "Regeneration Herb I",
		"purpose": "H_Regen",
		"buy_price": 10,
		"sell_price": 5,
		"required_level": 1,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 20
	},
	{
		"item_id": 1003,
		"name": "Healing Herb II",
		"purpose": "H_Heal",
		"buy_price": 50,
		"sell_price": 25,
		"required_level": 5,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 50
	},
	{
		"item_id": 1004,
		"name": "Regeneration Herb II",
		"purpose": "H_Regeneration",
		"buy_price": 50,
		"sell_price": 25,
		"required_level": 5,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 65
	},
	{
		"item_id": 1005,
		"name": "Healing Herb III",
		"purpose": "H_Heal",
		"buy_price": 100,
		"sell_price": 50,
		"required_level": 10,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 150
	},
	{
		"item_id": 1006,
		"name": "Regeneration Herb III",
		"purpose": "H_Regeneration",
		"buy_price": 100,
		"sell_price": 50,
		"required_level": 10,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 200
	},
	{
		"item_id": 1007,
		"name": "Healing Herb IV",
		"purpose": "H_Heal",
		"buy_price": 250,
		"sell_price": 125,
		"required_level": 20,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 200
	},
	{
		"item_id": 1008,
		"name": "Regeneration Herb IV",
		"purpose": "H_Regeneration",
		"buy_price": 250,
		"sell_price": 125,
		"required_level": 20,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 250
	},
	{
		"item_id": 1009,
		"name": "Healing Herb V",
		"purpose": "H_Heal",
		"buy_price": 500,
		"sell_price": 250,
		"required_level": 30,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 400
	},
	{
		"item_id": 1010,
		"name": "Regeneration Herb V",
		"purpose": "H_Regeneration",
		"buy_price": 500,
		"sell_price": 250,
		"required_level": 30,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 450
	},
	{
		"item_id": 1011,
		"name": "Healing Herb VI",
		"purpose": "H_Heal",
		"buy_price": 1000,
		"sell_price": 500,
		"required_level": 40,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 500
	},
	{
		"item_id": 1012,
		"name": "Regeneration Herb VI",
		"purpose": "H_Regeneration",
		"buy_price": 1000,
		"sell_price": 500,
		"required_level": 40,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 5,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 0,
		"value": 600
	},
	{
		"item_id": 1013,
		"name": "Healing Herb VII",
		"purpose": "H_Heal",
		"buy_price": 2000,
		"sell_price": 1000,
		"required_level": 50,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 0,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 5,
		"value": 500
	},
	{
		"item_id": 1014,
		"name": "Regeneration Herb VII",
		"purpose": "H_Regeneration",
		"buy_price": 2000,
		"sell_price": 1000,
		"required_level": 50,
		"buy_xp": 0,
		"sell_xp": 0,
		"consume_time": 0,
		"duration": 20,
		"interrupted_by_stun": 0,
		"interrupted_by_damage": 0,
		"interrupted_by_ability_use": 0,
		"interrupted_by_move": 0,
		"range": 5,
		"value": 1000
	}
];

module.exports = Items;
